spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: auto
        show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: mypassword
    initialization-mode: always
    initialize: true

---

spring:
  profiles: h2db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: create
        show-sql: true
    h2:
      console:
        enabled: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:demodb
    username: sa
    password:
    initialization-mode: always
    initialize: true
